CREATE TABLESPACE TBS_USERADISMONLAP DATAFILE 
  'D:\APP\ADI.SETIADI\ORADATA\ADIS\USERADISMMON.DBF' SIZE 4M AUTOEXTEND ON NEXT 1G MAXSIZE UNLIMITED
LOGGING
DEFAULT 
  NO INMEMORY
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;