CREATE TEMPORARY TABLESPACE TEMP_ADIS TEMPFILE 
  'D:\APP\ADI.SETIADI\ORADATA\ADIS\TEMP_ADIS.DBF' SIZE 129M AUTOEXTEND ON NEXT 640K MAXSIZE UNLIMITED
TABLESPACE GROUP ''
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1M;

