CREATE USER USERADISMONLAP IDENTIFIED BY adis123
 DEFAULT TABLESPACE TBS_USERADISMONLAP
 TEMPORARY TABLESPACE TEMP_ADIS
 QUOTA UNLIMITED ON TBS_USERADISMONLAP;

GRANT CREATE ANY CUBE TO USERADISMONLAP;

GRANT CREATE ANY CUBE BUILD PROCESS TO USERADISMONLAP;

GRANT CREATE ANY CUBE DIMENSION TO USERADISMONLAP;

GRANT CREATE ANY MEASURE FOLDER TO USERADISMONLAP;

GRANT CREATE ANY SYNONYM TO USERADISMONLAP;

GRANT CREATE ANY TABLE TO USERADISMONLAP;

GRANT CREATE ANY VIEW TO USERADISMONLAP;

GRANT CREATE JOB TO USERADISMONLAP;

GRANT CREATE SEQUENCE TO USERADISMONLAP;

GRANT CREATE SYNONYM TO USERADISMONLAP;

GRANT CREATE TABLE TO USERADISMONLAP;

GRANT CREATE TRIGGER TO USERADISMONLAP;

GRANT CREATE VIEW TO USERADISMONLAP;

GRANT DELETE ANY CUBE DIMENSION TO USERADISMONLAP;

GRANT DELETE ANY MEASURE FOLDER TO USERADISMONLAP;

GRANT DELETE ANY TABLE TO USERADISMONLAP;

GRANT DROP ANY CUBE TO USERADISMONLAP;

GRANT DROP ANY CUBE BUILD PROCESS TO USERADISMONLAP;

GRANT DROP ANY CUBE DIMENSION TO USERADISMONLAP;

GRANT DROP ANY MEASURE FOLDER TO USERADISMONLAP;

GRANT DROP ANY TABLE TO USERADISMONLAP;

GRANT DROP ANY VIEW TO USERADISMONLAP;

GRANT INSERT ANY CUBE DIMENSION TO USERADISMONLAP;

GRANT INSERT ANY MEASURE FOLDER TO USERADISMONLAP;

GRANT INSERT ANY TABLE TO USERADISMONLAP;

GRANT SELECT ANY CUBE TO USERADISMONLAP;

GRANT SELECT ANY CUBE DIMENSION TO USERADISMONLAP;

GRANT SELECT ANY TABLE TO USERADISMONLAP;

GRANT UPDATE ANY CUBE TO USERADISMONLAP;

GRANT UPDATE ANY CUBE BUILD PROCESS TO USERADISMONLAP;

GRANT UPDATE ANY CUBE DIMENSION TO USERADISMONLAP;

GRANT UPDATE ANY TABLE TO USERADISMONLAP;

grant create session to USERADISMONLAP ;


GRANT "CONNECT" TO USERADISMONLAP;
ALTER USER USERADISMONLAP DEFAULT ROLE NONE;

