SELECT c.*, a.USERNAME 
FROM USERADISMONLAP.VER_USERS a, USERADISMONLAP.VER_APP_ROLES b, USERADISMONLAP.VER_APP_LISTMENU c
where a.USERNAME = :vemiluser
and   a.ROLE = b.ROLE(+)
and   b.IDMENU = c.IDMENU(+)
and   b.IDMENU = c.IDMENU(+)