VARIABLE TMPCUR_OUT REFCURSOR;
DECLARE
  pesan varchar2(1000);
--  TMPCUR_OUT SYS_REFCURSOR;
BEGIN
 VER_MON_LAP.monlap_mivbelumflag_plnvsbank('202404', null, :TMPCUR_OUT, pesan);
 DBMS_OUTPUT.PUT_LINE(pesan);
END;
PRINT TMPCUR_OUT;