CREATE TABLE VER_MASTER_UNIT
(
  KD_DIST        VARCHAR2(2 BYTE),
  UNITAP_P2APST  VARCHAR2(3 BYTE),
  UNITAP_AP2T    VARCHAR2(3 BYTE),
  KD_ERP         VARCHAR2(3 BYTE),
  UNITUP         VARCHAR2(5 BYTE),
  NAMA_DIST      VARCHAR2(30 BYTE),
  NAMA_AREA      VARCHAR2(30 BYTE),
  NAMA_UNIT      VARCHAR2(35 BYTE),
  ALAMAT_UNIT    VARCHAR2(50 BYTE),
  KET            CHAR(4 BYTE)
);


CREATE INDEX VER_MASTER_UNIT ON VER_MASTER_UNIT
(KD_DIST, UNITUP);
