CREATE TABLE VER_MASTER_BANK
(
  KODE_ERP   VARCHAR2(7 BYTE),
  KODE_BANK  VARCHAR2(3 BYTE),
  NAMA_BANK  VARCHAR2(30 BYTE),
  STATUS     VARCHAR2(1 BYTE)
);


CREATE UNIQUE INDEX IDX_VER_MASTER_BANK ON VER_MASTER_BANK
(KODE_BANK);

ALTER TABLE VER_MASTER_BANK ADD (
  CONSTRAINT IDX_VER_MASTER_BANK
  PRIMARY KEY
  (KODE_BANK)
  USING INDEX IDX_VER_MASTER_BANK
  ENABLE VALIDATE);
