CREATE TABLE VER_TEMP_DATA_LOCKING
(
  KD_DIST      VARCHAR2(2 BYTE),
  NOUSULAN     VARCHAR2(20 BYTE),
  TGLUSULAN    VARCHAR2(8 BYTE)                 DEFAULT TO_CHAR(SYSDATE,'yyyymmdd'),
  IDPEL        VARCHAR2(12 BYTE),
  BLTH         VARCHAR2(6 BYTE),
  RPTAG        NUMBER(12),
  RPBK         NUMBER(12),
  USERID       VARCHAR2(25 BYTE),
  KDPROSES     VARCHAR2(50 BYTE),
  USERID_LOCK  VARCHAR2(25 BYTE)                NOT NULL,
  STATUS       NUMBER(1)                        DEFAULT 0,
  KETERANGAN   VARCHAR2(100 BYTE),
  VA           VARCHAR2(20 BYTE),
  KDBANK       VARCHAR2(7 BYTE),
  SATKER       VARCHAR2(200 BYTE),
  TGLINSERT    DATE,
  IDKIRIM      VARCHAR2(60 BYTE)                DEFAULT 0                     NOT NULL,
  SUPPLEMENTAL LOG GROUP GGS_21901 (KD_DIST,NOUSULAN,TGLUSULAN,IDPEL,BLTH,STATUS,KDPROSES) ALWAYS
);


CREATE INDEX IDX_VER_TEM_DATA_LOCK_IDKIRIM ON VER_TEMP_DATA_LOCKING
(IDKIRIM);

CREATE UNIQUE INDEX PK_TEMP_DATA_LOCKING ON VER_TEMP_DATA_LOCKING
(KD_DIST, NOUSULAN, TGLUSULAN, KDPROSES, IDPEL, 
BLTH, STATUS);
