CREATE TABLE VER_TEMP_DATA_LOCKING_NTL
(
  KD_DIST      VARCHAR2(2 BYTE),
  NOUSULAN     VARCHAR2(20 BYTE),
  TGLUSULAN    VARCHAR2(8 BYTE)                 DEFAULT TO_CHAR(SYSDATE,'yyyymmdd'),
  NOREG        VARCHAR2(13 BYTE),
  RPTAG        NUMBER(13),
  USERID       VARCHAR2(25 BYTE),
  KDPROSES     VARCHAR2(50 BYTE),
  USERID_LOCK  VARCHAR2(25 BYTE)                NOT NULL,
  STATUS       NUMBER(1)                        DEFAULT 0,
  KETERANGAN   VARCHAR2(100 BYTE),
  VA           VARCHAR2(20 BYTE),
  KDBANK       VARCHAR2(7 BYTE),
  SATKER       VARCHAR2(200 BYTE),
  TGLINSERT    DATE,
  SUPPLEMENTAL LOG GROUP GGS_21932 (KD_DIST,NOUSULAN,TGLUSULAN,NOREG,STATUS,KDPROSES) ALWAYS
);


CREATE UNIQUE INDEX PK_TEMP_DATA_LOCKING_NTL ON VER_TEMP_DATA_LOCKING_NTL
(KD_DIST, NOUSULAN, TGLUSULAN, KDPROSES, NOREG, 
STATUS);