CREATE TABLE VER_DATA_LOCKING_BANK_NTL
(
  NOUSULAN   VARCHAR2(20 BYTE),
  TGLUSULAN  VARCHAR2(8 BYTE)                   DEFAULT TO_CHAR(SYSDATE,'yyyymmdd'),
  VA         VARCHAR2(20 BYTE),
  KDBANK     VARCHAR2(7 BYTE),
  NOREG      VARCHAR2(13 BYTE),
  RPTAG      NUMBER(12),
  TGLBAYAR   VARCHAR2(10 BYTE),
  JAMBAYAR   VARCHAR2(6 BYTE),
  USERID     VARCHAR2(25 BYTE)                  NOT NULL,
  NAMAFILE   VARCHAR2(50 BYTE),
  TGLINSERT  DATE,
  SUPPLEMENTAL LOG GROUP GGS_21908 (NOUSULAN,TGLUSULAN,NOREG) ALWAYS
);


CREATE UNIQUE INDEX IDX_VER_DATA_LOCK_BANK_NTL ON VER_DATA_LOCKING_BANK_NTL
(NOUSULAN, TGLUSULAN, VA, KDBANK, NOREG);