CREATE TABLE MASTER_DISTRIBUSI
(
  KD_DIST         VARCHAR2(2 BYTE)              NOT NULL,
  NAMA_DIST       VARCHAR2(40 BYTE),
  ALAMAT          VARCHAR2(50 BYTE),
  SINGKATAN_DIST  VARCHAR2(10 BYTE),
  MBN             VARCHAR2(30 BYTE),
  TGL_AKTIF       VARCHAR2(8 BYTE),
  USERDIST        VARCHAR2(10 BYTE),
  NAMADIST        VARCHAR2(50 BYTE),
  AP2T            VARCHAR2(1 BYTE),
  UNITREG         VARCHAR2(2 BYTE),
  SUPPLEMENTAL LOG GROUP GGS_23261 (KD_DIST) ALWAYS
);


CREATE INDEX IDX_MASTER_DISTRIBUSI ON MASTER_DISTRIBUSI
(NAMADIST);

CREATE INDEX MD_COMP_IDX_01 ON MASTER_DISTRIBUSI
(KD_DIST, NAMA_DIST);

CREATE INDEX MD_COMP_IDX_02 ON MASTER_DISTRIBUSI
(KD_DIST, SINGKATAN_DIST);

CREATE UNIQUE INDEX PK_MASTER_DISTRIBUSI ON MASTER_DISTRIBUSI
(KD_DIST);