CREATE TABLE VER_TEMP_DATA_LOCKING_SAKTI
(
  BLTH_USUL    VARCHAR2(6 BYTE),
  ID_USUL      VARCHAR2(20 BYTE),
  IDPEL        VARCHAR2(12 BYTE),
  BLTH         VARCHAR2(6 BYTE),
  KD_DIST      VARCHAR2(2 BYTE),
  RPTAG        NUMBER(12),
  RPMAT        NUMBER(12),
  KDPROSES     VARCHAR2(50 BYTE),
  USERID_LOCK  VARCHAR2(25 BYTE)                NOT NULL,
  STATUS       NUMBER(1)                        DEFAULT 0,
  KETERANGAN   VARCHAR2(100 BYTE),
  VA           VARCHAR2(20 BYTE),
  KDBANK       VARCHAR2(7 BYTE),
  SATKER       VARCHAR2(200 BYTE),
  TGLINSERT    DATE,
  IDKIRIM      VARCHAR2(60 BYTE)                DEFAULT 0                     NOT NULL
);


CREATE UNIQUE INDEX PK_VER_TEMP_DATA_LOCKING_SAKTI ON VER_TEMP_DATA_LOCKING_SAKTI
(BLTH_USUL, ID_USUL, IDPEL, BLTH, KD_DIST, 
KDPROSES);

CREATE INDEX VER_TEM_DATA_LOCK_SAKTI_KIRIM ON VER_TEMP_DATA_LOCKING_SAKTI
(IDKIRIM);