CREATE TABLE MASTER_BANK
(
  KODE_ERP    VARCHAR2(7 BYTE),
  SANDI       VARCHAR2(7 BYTE),
  KODE_BANK   VARCHAR2(3 BYTE),
  NAMA_BANK   VARCHAR2(30 BYTE),
  KANTOR      VARCHAR2(30 BYTE),
  ALAMAT      VARCHAR2(50 BYTE),
  KOTA        VARCHAR2(30 BYTE),
  STAT        VARCHAR2(4 BYTE),
  CLT         VARCHAR2(1 BYTE),
  SWITCHERID  VARCHAR2(7 BYTE),
  STATUS      VARCHAR2(1 BYTE),
  TELEPON     VARCHAR2(30 BYTE),
  FAX         VARCHAR2(30 BYTE),
  EMAIL       VARCHAR2(1000 BYTE),
  SUPPLEMENTAL LOG GROUP GGS_22029 (KODE_ERP) ALWAYS
);


CREATE INDEX IDX_MASTER_BANK_SND ON MASTER_BANK
(SANDI);

CREATE UNIQUE INDEX MASTER_BANK_PK ON MASTER_BANK
(KODE_ERP);