CREATE TABLE MASTER_UNIT
(
  KD_DIST          VARCHAR2(2 BYTE),
  NAMA_DIST        VARCHAR2(30 BYTE),
  KD_AREA          CHAR(3 BYTE),
  AREA             VARCHAR2(3 BYTE),
  NAMA_AREA        VARCHAR2(30 BYTE),
  KD_UNIT          CHAR(5 BYTE),
  UNITUP           VARCHAR2(5 BYTE),
  NAMA             VARCHAR2(30 BYTE),
  NAMA_UNIT        VARCHAR2(30 BYTE),
  ALAMAT           VARCHAR2(50 BYTE),
  ALAMAT_UNIT      VARCHAR2(50 BYTE),
  IPAPPSVR         VARCHAR2(15 BYTE),
  IPDBCARGO        VARCHAR2(15 BYTE),
  TELEPON          VARCHAR2(30 BYTE),
  FACSIMILI        VARCHAR2(15 BYTE),
  EMAIL            VARCHAR2(35 BYTE),
  SMS_CENTER       VARCHAR2(25 BYTE),
  IP_VENDING_UNIT  VARCHAR2(15 BYTE),
  KD_REGION        CHAR(2 BYTE),
  KD_ZONE          CHAR(3 BYTE),
  TAG_INFO         VARCHAR2(60 BYTE),
  KD_ERP           VARCHAR2(3 BYTE),
  UNIT_ERP         VARCHAR2(30 BYTE),
  AKUN_WIL         VARCHAR2(10 BYTE),
  KD_SSU           VARCHAR2(1 BYTE),
  NM_AREA          VARCHAR2(30 BYTE),
  NM_UNIT          VARCHAR2(30 BYTE),
  SUPPLEMENTAL LOG GROUP GGS_23262 (UNITUP) ALWAYS
);


CREATE UNIQUE INDEX PK_MASTER_UNIT ON MASTER_UNIT
(UNITUP);
