CREATE TABLE USERADISMONLAP.VER_MASTER_BANK
(
  KODE_ERP   VARCHAR2(7 BYTE),
  KODE_BANK  VARCHAR2(3 BYTE),
  NAMA_BANK  VARCHAR2(30 BYTE),
  STATUS     VARCHAR2(1 BYTE)
);


CREATE UNIQUE INDEX USERADISMONLAP.IDX_VER_MASTER_BANK ON USERADISMONLAP.VER_MASTER_BANK
(KODE_BANK);

ALTER TABLE USERADISMONLAP.VER_MASTER_BANK ADD (
  CONSTRAINT IDX_VER_MASTER_BANK
  PRIMARY KEY
  (KODE_BANK);
  
  
--insert Data
SET DEFINE OFF;
Insert into USERADISMONLAP.VER_MASTER_BANK
   (KODE_ERP, KODE_BANK, NAMA_BANK, STATUS)
 Values
   ('2000001', '200', 'BANK TABUNGAN NEGARA', '1');
Insert into USERADISMONLAP.VER_MASTER_BANK
   (KODE_ERP, KODE_BANK, NAMA_BANK, STATUS)
 Values
   ('0080017', '008', 'BANK MANDIRI', '1');
Insert into USERADISMONLAP.VER_MASTER_BANK
   (KODE_ERP, KODE_BANK, NAMA_BANK, STATUS)
 Values
   ('0090010', '009', 'BANK BNI', '1');
Insert into USERADISMONLAP.VER_MASTER_BANK
   (KODE_ERP, KODE_BANK, NAMA_BANK, STATUS)
 Values
   ('1110013', '111', 'BANK DKI', '1');
Insert into USERADISMONLAP.VER_MASTER_BANK
   (KODE_ERP, KODE_BANK, NAMA_BANK, STATUS)
 Values
   ('4410010', '441', 'BANK BUKOPIN', '1');
COMMIT;
