CREATE TABLE USERADISMONLAP.MASTER_DISTRIBUSI
(
  KD_DIST         VARCHAR2(2 BYTE)              NOT NULL,
  NAMA_DIST       VARCHAR2(40 BYTE),
  ALAMAT          VARCHAR2(50 BYTE),
  SINGKATAN_DIST  VARCHAR2(10 BYTE),
  MBN             VARCHAR2(30 BYTE),
  TGL_AKTIF       VARCHAR2(8 BYTE),
  USERDIST        VARCHAR2(10 BYTE),
  NAMADIST        VARCHAR2(50 BYTE),
  AP2T            VARCHAR2(1 BYTE),
  UNITREG         VARCHAR2(2 BYTE),
  SUPPLEMENTAL LOG GROUP GGS_23261 (KD_DIST) ALWAYS
);


CREATE INDEX USERADISMONLAP.IDX_MASTER_DISTRIBUSI ON USERADISMONLAP.MASTER_DISTRIBUSI
(NAMADIST);

--insert data
SET DEFINE OFF;
Insert into USERADISMONLAP.MASTER_DISTRIBUSI
   (KD_DIST, NAMA_DIST, SINGKATAN_DIST, TGL_AKTIF, USERDIST, 
    NAMADIST, UNITREG)
 Values
   ('56', 'BANTEN', 'BANTEN', '20160110', 'USRBANTEN', 
    'UID BANTEN', '02');
Insert into USERADISMONLAP.MASTER_DISTRIBUSI
   (KD_DIST, NAMA_DIST, ALAMAT, SINGKATAN_DIST, MBN, 
    TGL_AKTIF, USERDIST, NAMADIST, UNITREG)
 Values
   ('11', 'ACEH', 'JL TGK MOHD DAUD BEUREUH NO 172 BANDA ACEH', 'ACEH', 'HUSAINI MOEIN', 
    '20110601', 'USRACEH', 'UIW ACEH', '01');
Insert into USERADISMONLAP.MASTER_DISTRIBUSI
   (KD_DIST, NAMA_DIST, ALAMAT, SINGKATAN_DIST, MBN, 
    TGL_AKTIF, USERDIST, NAMADIST, UNITREG)
 Values
   ('14', 'S2JB', 'JL KAPTEN A RIVAI NO 37 PALEMBANG', 'S2JB', 'ARIS SUMARTONO', 
    '20110601', 'USRS2JB', 'UIW S2JB', '01');
Insert into USERADISMONLAP.MASTER_DISTRIBUSI
   (KD_DIST, NAMA_DIST, ALAMAT, SINGKATAN_DIST, TGL_AKTIF, 
    USERDIST, NAMADIST, AP2T, UNITREG)
 Values
   ('15', 'PLN BATAM', 'JL ENGKU PUTRI BATAM CENTRE BATAM', 'BATAM', '20111001', 
    'USRBATAM', 'BATAM', '1', '08');
Insert into USERADISMONLAP.MASTER_DISTRIBUSI
   (KD_DIST, NAMA_DIST, ALAMAT, SINGKATAN_DIST, MBN, 
    TGL_AKTIF, USERDIST, NAMADIST, UNITREG)
 Values
   ('16', 'BANGKA BELITUNG', 'JL JEND SUDIRMAN NO 180 PANGKAL PINANG', 'BABEL', 'ERIADI DJAMAAN', 
    '20110401', 'USRBABEL', 'UIW BANGKA BELITUNG', '01');
Insert into USERADISMONLAP.MASTER_DISTRIBUSI
   (KD_DIST, NAMA_DIST, ALAMAT, SINGKATAN_DIST, TGL_AKTIF, 
    USERDIST, NAMADIST, UNITREG)
 Values
   ('21', 'KALIMANTAN BARAT', 'JL ADI SUCIPTO KM 7,3 SEI RAYA PONTIANAK', 'KALBAR', '20110429', 
    'USRKALBAR', 'UIW KALIMANTAN BARAT', '05');
Insert into USERADISMONLAP.MASTER_DISTRIBUSI
   (KD_DIST, NAMA_DIST, ALAMAT, SINGKATAN_DIST, MBN, 
    TGL_AKTIF, USERDIST, NAMADIST, UNITREG)
 Values
   ('22', 'KALIMANTAN SELATAN DAN TENGAH', 'JL PANGLIMA BATUR BARAT NO 1 BANJAR BARU', 'KALSEL', 'SYAWALUDIN SOFYAN', 
    '20110201', 'USRKALSEL', 'UIW KALIMANTAN SELATAN DAN TENGAH', '05');
Insert into USERADISMONLAP.MASTER_DISTRIBUSI
   (KD_DIST, NAMA_DIST, ALAMAT, SINGKATAN_DIST, TGL_AKTIF, 
    USERDIST, NAMADIST, UNITREG)
 Values
   ('41', 'MALUKU DAN MALUKU UTARA', 'JL DIPONEGORO NO 2 AMBON', 'MALUKU', '20110701', 
    'USRMALUKU', 'UIW MALUKU DAN MALUKU UTARA', '07');
Insert into USERADISMONLAP.MASTER_DISTRIBUSI
   (KD_DIST, NAMA_DIST, ALAMAT, SINGKATAN_DIST, MBN, 
    TGL_AKTIF, USERDIST, NAMADIST, UNITREG)
 Values
   ('42', 'PAPUA DAN PAPUA BARAT', 'JL JEND AHMAD YANI NO 18 JAYAPURA', 'PAPUA', 'TISNA GUNAWAN', 
    '20110601', 'USRPAPUA', 'UIW PAPUA DAN PAPUA BARAT', '07');
Insert into USERADISMONLAP.MASTER_DISTRIBUSI
   (KD_DIST, NAMA_DIST, ALAMAT, SINGKATAN_DIST, MBN, 
    TGL_AKTIF, USERDIST, NAMADIST, UNITREG)
 Values
   ('44', 'NUSA TENGGARA BARAT', 'JL LANGKO NO 25-27 MATARAM', 'NTB', 'ANGGORO TJIPTOHARTO', 
    '20110201', 'USRNTB', 'UIW NUSA TENGGARA BARAT', '04');
Insert into USERADISMONLAP.MASTER_DISTRIBUSI
   (KD_DIST, NAMA_DIST, SINGKATAN_DIST, USERDIST, NAMADIST)
 Values
   ('25', 'PLN TARAKAN', 'TARAKAN', 'USRTARAKAN', 'TARAKAN');
Insert into USERADISMONLAP.MASTER_DISTRIBUSI
   (KD_DIST, NAMA_DIST, ALAMAT, SINGKATAN_DIST, MBN, 
    TGL_AKTIF, USERDIST, NAMADIST, AP2T, UNITREG)
 Values
   ('53', 'JAWA BARAT', 'JL ASIA AFRIKA NO 63 BANDUNG', 'DJBB', 'MOH.MUNIEF BUDIMAN', 
    '20071001', 'USRJABAR', 'UID JAWA BARAT', '1', '03');
Insert into USERADISMONLAP.MASTER_DISTRIBUSI
   (KD_DIST, NAMA_DIST, ALAMAT, SINGKATAN_DIST, MBN, 
    TGL_AKTIF, USERDIST, NAMADIST, AP2T, UNITREG)
 Values
   ('54', 'JAKARTA RAYA', 'JL M.I.R.RAIS NO 1 JAKARTA', 'DISJAYA', 'DWI KUSNANTO', 
    '20100501', 'USRDKI', 'UID JAKARTA RAYA', '1', '02');
Insert into USERADISMONLAP.MASTER_DISTRIBUSI
   (KD_DIST, NAMA_DIST, ALAMAT, SINGKATAN_DIST, MBN, 
    TGL_AKTIF, USERDIST, NAMADIST, AP2T, UNITREG)
 Values
   ('55', 'BALI', 'JL LETDA TANTULAR NO 1 RENON', 'BALI', 'SYAMSUL HUDA', 
    '20100101', 'USRBALI', 'UID BALI', '1', '04');
Insert into USERADISMONLAP.MASTER_DISTRIBUSI
   (KD_DIST, NAMA_DIST, ALAMAT, SINGKATAN_DIST, MBN, 
    TGL_AKTIF, USERDIST, NAMADIST, AP2T, UNITREG)
 Values
   ('52', 'JAWA TENGAH DAN DIY', 'JL TEUKU UMAR NO 47 SEMARANG', 'DJTY', 'ROBERTON MANURUNG', 
    '20100201', 'USRJATENG', 'UID JAWA TENGAH DAN DIY', '1', '03');
Insert into USERADISMONLAP.MASTER_DISTRIBUSI
   (KD_DIST, NAMA_DIST, ALAMAT, SINGKATAN_DIST, MBN, 
    TGL_AKTIF, USERDIST, NAMADIST, AP2T, UNITREG)
 Values
   ('51', 'JAWA TIMUR', 'JL EMBONG TRENGGULI No 19-21 SURABAYA', 'JATIM', 'I MADE ARTHA', 
    '20100601', 'USRJATIM', 'UID JAWA TIMUR', '1', '04');
Insert into USERADISMONLAP.MASTER_DISTRIBUSI
   (KD_DIST, NAMA_DIST, ALAMAT, SINGKATAN_DIST, MBN, 
    TGL_AKTIF, USERDIST, NAMADIST, AP2T, UNITREG)
 Values
   ('17', 'LAMPUNG', 'JL ZA. PAGAR ALAM N0 5 BANDAR LAMPUNG', 'LAMPUNG', 'RAHIMUDDIN', 
    '20110401', 'USRLAMPUNG', 'UID LAMPUNG', '1', '01');
Insert into USERADISMONLAP.MASTER_DISTRIBUSI
   (KD_DIST, NAMA_DIST, ALAMAT, SINGKATAN_DIST, MBN, 
    TGL_AKTIF, USERDIST, NAMADIST, AP2T, UNITREG)
 Values
   ('12', 'SUMATERA UTARA', 'JL K.L YOS SUDARSO NO 284 MEDAN', 'SUMUT', 'MIRZA ARSYAD', 
    '20101201', 'USRSUMUT', 'UIW SUMATERA UTARA', '1', '01');
Insert into USERADISMONLAP.MASTER_DISTRIBUSI
   (KD_DIST, NAMA_DIST, ALAMAT, SINGKATAN_DIST, MBN, 
    TGL_AKTIF, USERDIST, NAMADIST, UNITREG)
 Values
   ('23', 'KALIMANTAN TIMUR', 'JL MT HARYONO NO 384 BALIKPAPAN', 'KALTIM', 'TOHARI HADIAT', 
    '20101001', 'USRKALTIM', 'UIW KALIMANTAN TIMUR', '05');
Insert into USERADISMONLAP.MASTER_DISTRIBUSI
   (KD_DIST, NAMA_DIST, ALAMAT, SINGKATAN_DIST, MBN, 
    TGL_AKTIF, USERDIST, NAMADIST, UNITREG)
 Values
   ('43', 'NUSA TENGGARA TIMUR', 'JL PALAPA NO 27 KUPANG', 'NTT', 'M MUNIEF BUDIMAN', 
    '20101101', 'USRNTT', 'UIW NUSA TENGGARA TIMUR', '04');
Insert into USERADISMONLAP.MASTER_DISTRIBUSI
   (KD_DIST, NAMA_DIST, ALAMAT, SINGKATAN_DIST, MBN, 
    TGL_AKTIF, USERDIST, NAMADIST, AP2T, UNITREG)
 Values
   ('13', 'SUMATERA BARAT', 'JL DR WAHIDIN NO 8 PADANAG', 'SUMBAR', 'BAMBANG YUSUF', 
    '20110301', 'USRSUMBAR', 'UIW SUMATERA BARAT', '1', '01');
Insert into USERADISMONLAP.MASTER_DISTRIBUSI
   (KD_DIST, NAMA_DIST, ALAMAT, SINGKATAN_DIST, MBN, 
    TGL_AKTIF, USERDIST, NAMADIST, UNITREG)
 Values
   ('32', 'SULSELRABAR', 'JL LETJEN HERTASNING BLOK B MAKASSAR', 'SULSEL', 'DYANANTO', 
    '20110301', 'USRSULSEL', 'UIW SULSELRABAR', '06');
Insert into USERADISMONLAP.MASTER_DISTRIBUSI
   (KD_DIST, NAMA_DIST, ALAMAT, SINGKATAN_DIST, TGL_AKTIF, 
    USERDIST, NAMADIST, AP2T, UNITREG)
 Values
   ('31', 'SULUTTENGGO', 'JL BETHESDA NO 32 MANADO', 'SULUT', '20110429', 
    'USRSULUT', 'UIW SULUTTENGGO', '1', '06');
Insert into USERADISMONLAP.MASTER_DISTRIBUSI
   (KD_DIST, NAMA_DIST, ALAMAT, SINGKATAN_DIST, MBN, 
    TGL_AKTIF, USERDIST, NAMADIST, AP2T, UNITREG)
 Values
   ('18', 'RIAU DAN KEPRI', 'JL DR SETIABUDI NO 57 PEKANBARU', 'KEPRI', 'BAMBANG SETYO HADI', 
    '20110401', 'USRKEPRI', 'UIW RIAU DAN KEPRI', '1', '01');
COMMIT;
