CREATE TABLE USERADISMONLAP.TRANSAKSI_PREPAID
(
  KD_DIST          VARCHAR2(2 BYTE),
  UNITUP           VARCHAR2(5 BYTE),
  NOMOR_METER_KWH  VARCHAR2(20 BYTE),
  IDPEL            VARCHAR2(12 BYTE),
  KDPP             VARCHAR2(14 BYTE),
  PEMDA            VARCHAR2(2 BYTE),
  NAMA             VARCHAR2(25 BYTE),
  TARIP            VARCHAR2(4 BYTE),
  DAYA             NUMBER(6),
  KDAYA            VARCHAR2(1 BYTE),
  KOGOL            VARCHAR2(4 BYTE),
  PEMKWH           NUMBER(9,2),
  RPPTL            NUMBER(11,2),
  RPPPN            NUMBER(10,2),
  RPBPJU           NUMBER(10,2),
  RPMAT            NUMBER(6),
  RP_ANGSURAN      NUMBER(11,2),
  RPTAG            NUMBER(11,2),
  TGLBAYAR         VARCHAR2(8 BYTE),
  JAMBAYAR         VARCHAR2(8 BYTE),
  USERID           VARCHAR2(20 BYTE),
  BAD              NUMBER(1),
  NOMOR_TOKEN      VARCHAR2(20 BYTE),
  TGL_REKON        VARCHAR2(8 BYTE),
  USER_REKON       VARCHAR2(10 BYTE),
  UNSOLD           VARCHAR2(1 BYTE),
  KIRIM            VARCHAR2(1 BYTE),
  TGLSETTLE        VARCHAR2(8 BYTE),
  REFNUM           VARCHAR2(32 BYTE),
  SREFNUM          VARCHAR2(32 BYTE),
  MERCHANT         VARCHAR2(4 BYTE),
  TGLKIRIM         VARCHAR2(8 BYTE),
  JAMINSERT        DATE,
  TGUPDATE         VARCHAR2(8 BYTE),
  JAMUPDATE        VARCHAR2(6 BYTE),
  RC               VARCHAR2(3 BYTE),
  NOBATCH          VARCHAR2(5 BYTE),
  KD_DPT           CHAR(2 BYTE),
  KD_DPT_VALID     CHAR(1 BYTE),
  NO_DPT           VARCHAR2(20 BYTE),
  KIRIMDB          VARCHAR2(1 BYTE),
  RPPTL2           NUMBER(11,2),
  RPPPN2           NUMBER(10,2),
  RPBPJU2          NUMBER(10,2),
  RP_ANGSURAN2     NUMBER(11,2)
);

ALTER TABLE USERADISMONLAP.TRANSAKSI_PREPAID ADD (
  CONSTRAINT PK_TRANSAKSI_PREPAID_NEW
  PRIMARY KEY
  (NOMOR_TOKEN));
  
  