CREATE TABLE USERADISMONLAP.VER_DATA_LOCKING_BANK_PRE
(
  NOUSULAN   VARCHAR2(20 BYTE),
  TGLUSULAN  VARCHAR2(8 BYTE)                   DEFAULT TO_CHAR(SYSDATE,'yyyymmdd'),
  VA         VARCHAR2(20 BYTE),
  KDBANK     VARCHAR2(7 BYTE),
  IDPEL      VARCHAR2(12 BYTE),
  BLTH       VARCHAR2(6 BYTE),
  RPTAG      NUMBER(12),
  TGLBAYAR   VARCHAR2(10 BYTE),
  JAMBAYAR   VARCHAR2(6 BYTE),
  USERID     VARCHAR2(25 BYTE)                  NOT NULL,
  NAMAFILE   VARCHAR2(50 BYTE),
  TGLINSERT  DATE,
  SUPPLEMENTAL LOG GROUP GGS_21907 (NOUSULAN,TGLUSULAN,IDPEL,BLTH) ALWAYS
);


CREATE UNIQUE INDEX USERADISMONLAP.IDX_VER_DATA_LOCK_BANK_PRE ON USERADISMONLAP.VER_DATA_LOCKING_BANK_PRE
(NOUSULAN, TGLUSULAN, VA, KDBANK, IDPEL, 
BLTH);