CREATE TABLE VER_RCN_BANK_LOG
(
  IDKIRIM VARCHAR2(60), 
  NOUSULAN VARCHAR2(21), 
  TGLUSULAN VARCHAR2(8), 
  JML_SUKSES NUMBER(12,2), 
  JML_GAGAL NUMBER(12,2), 
  RPTAG NUMBER(12,2), 
  KET VARCHAR2(50), 
  USERID VARCHAR2(25), 
  NAMAFILE VARCHAR2(50), 
  TGLINSERT date
);

CREATE INDEX VER_RCN_BANK_LOG ON VER_RCN_BANK_LOG
(NAMAFILE)