CREATE TABLE VER_DATA_LOCKING_BANK_PRE_CTL
(
  NAMAFILE  VARCHAR2(50 BYTE)                   NOT NULL,
  LEMBAR    NUMBER(15,2),
  RPTAG     NUMBER(15,2)
);


CREATE UNIQUE INDEX IDX_VER_DATA_LOCK_BANK_PRE_CTL ON VER_DATA_LOCKING_BANK_PRE_CTL
(NAMAFILE);